apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: github-tests-nodejs-wlkhhscy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: github-tests-nodejs-wlkhhscy 
  name: github-tests-nodejs-wlkhhscy
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: github-tests-nodejs-wlkhhscy 
